# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('work_phone_number', models.CharField(max_length=20)),
                ('mobile_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=500)),
                ('committee', models.CharField(max_length=500)),
                ('hotel_room_number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('delegate_count_estimate', models.IntegerField()),
                ('transportation_required', models.BooleanField()),
                ('interested_crisis_committees', models.BooleanField()),
                ('interested_ipd_positions', models.BooleanField()),
                ('top_three_positions', models.TextField(blank=True)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delegate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisornetwork.School'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisornetwork.School'),
        ),
    ]
