# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='hotel_room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='work_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='committee',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='hotel_room_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='position',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
