# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 01:38
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0002_auto_20160925_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='mobile_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='work_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
