# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0003_auto_20160929_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='paid_delegate_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='paid_school_fee',
            field=models.BooleanField(default=False),
        ),
    ]
