# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0004_auto_20160929_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='additional_registration_notes',
            field=models.TextField(blank=True),
        ),
    ]
