# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0006_auto_20160930_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='marked_paid_delegate_fee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='marked_paid_transit_fee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
