# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 01:04
from __future__ import unicode_literals

import advisornetwork.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0007_auto_20160930_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(upload_to=advisornetwork.models.pos_paper_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='advisornetwork.School'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='advisornetwork.School'),
        ),
        migrations.AddField(
            model_name='positionpaper',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_papers', to='advisornetwork.Delegate'),
        ),
    ]
