# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 23:41
from __future__ import unicode_literals

import advisornetwork.models
import advisornetwork.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornetwork', '0008_auto_20170127_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_copies', models.IntegerField()),
                ('committee', models.CharField(blank=True, choices=[('Ad-Hoc', 'Ad-Hoc'), ('Kingdom of Heaven: The Court of Baldwin IV of Jerusalem', 'Kingdom of Heaven: The Court of Baldwin IV of Jerusalem'), ('Responsibility to Protect: Coalition Forces (JCC)', 'Responsibility to Protect: Coalition Forces (JCC)'), ('Destiny Awaits: Iraqi Government (JCC)', 'Destiny Awaits: Iraqi Government (JCC)'), ('The Next Great City: The FIFA Executive Board Committee', 'The Next Great City: The FIFA Executive Board Committee'), ("Independence: Nehru's Cabinet of 1947", "Independence: Nehru's Cabinet of 1947"), ('Island of Mystery: The Roanoke Colony', 'Island of Mystery: The Roanoke Colony'), ('UNSC 2017: The World at Crossroads', 'UNSC 2017: The World at Crossroads'), ('1917 Duma', '1917 Duma'), ('DISEC', 'DISEC'), ('ECOFIN', 'ECOFIN'), ('ECOSOC', 'ECOSOC'), ('Illinois General Assembly', 'Illinois General Assembly'), ('International Press Delegation', 'International Press Delegation'), ('UNHRC', 'UNHRC'), ('WHO', 'WHO')], max_length=500)),
                ('comments', models.TextField(blank=True)),
                ('document', models.FileField(upload_to=advisornetwork.models.print_doc_path, validators=[advisornetwork.validators.validate_pos_paper_extension])),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='positionpaper',
            name='paper',
            field=models.FileField(upload_to=advisornetwork.models.pos_paper_path, validators=[advisornetwork.validators.validate_pos_paper_extension]),
        ),
    ]
